### PR TITLE
fix #4 issue

### LINKED ISSUE #4: Incompatible character encodings: ASCII-8BIT and UTF-8
Dear Tomáš,
Using RVM (v1.2.2) + Phusion Passenger (v3.0.2) + different versions of Ruby using RVM: ruby 1.8.7 (patchlevel 330) and ruby 1.9.2  + Rails 3.0.3 on Ubuntu Server 10.04, the application is running after using the "magic encoding" gem. However, Serenity ODT, render_odt is generating the following error:
incompatible character encodings: ASCII-8BIT and UTF-8
Do you an idea and a fix for the library which is very useful for me!
Thanks a lot in advance,
Best Regards,
Lionel.

### PR DESCRIPTION
**Pull request by Wolfer**
fix Incompatible character encodings: ASCII-8BIT and UTF-8

### CODE REVIEW

**Comment by txapelgorri** [comment]
Oh, yes please merge this. I can confirm that I have the same issue on Ruby 2.0.0. Found a tip about the workaround here also: http://stackoverflow.com/questions/17339381/serenity-odt-under-ruby-2-0-encodingcompatibilityerror

**Comment by txapelgorri** [comment]
Thanks, awesome! :)

**Comment by kremso** [comment]
Thanks, merged. Please, if anyone of you would like to take over this project, I'd be happy to transfer it as I'm not using or maintaining it anymore.

**Comment by txapelgorri** [comment]
@kremso I wrote you an email about this: I have some spare hours a week to collaborate, and I would love to spend them in this project :)

**Pull request merged**
